# Generated by Django 3.1.3 on 2020-11-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201128_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsession',
            name='name',
            field=models.CharField(default='Room', max_length=30),
        ),
        migrations.AddField(
            model_name='editsessionallowed',
            name='shared_as',
            field=models.CharField(default='Room', max_length=30),
        ),
    ]
