# Generated by Django 3.1.3 on 2020-11-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201128_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editsessionallowed',
            name='date_shared',
        ),
        migrations.RemoveField(
            model_name='editsessionallowed',
            name='shared_as',
        ),
    ]
