# Generated by Django 3.1.3 on 2020-11-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20201128_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editsessionallowed',
            old_name='session_id',
            new_name='session',
        ),
    ]
